# Name: May Deng
# Course: CS 178 Build Automation for DevOps and QA
# CRN: 76718
# Date: 9/7/19
# Assignment: Compiling C code Makefile

# This Makefile is for compiling C code.

Count3s:
	gcc CountThreesC/countThrees.c CountThreesC/readInt32BitLE.c -o Count3s
runCount3s:
	./Count3s threesData.bin
